language: "node_js"
node_js: "node"
services: "mysql"
cache:
  directories:
    - "node_modules"
  yarn: true
addons:
  apt:
    sources:
      - "mysql-5.7-trusty"
    packages:
      - "mysql-server"
      - "mysql-client"
